#ifndef GH_OS_H
#define GH_OS_H

#define APP_EXIT_CODE_ALL_CLEAR 0
#define APP_EXIT_CODE_STDOUT_HANDLE 1
#define APP_EXIT_CODE_CONSOLE_MODE 2
#define APP_EXIT_CODE_ARGS_COUNT_IS_BAD 3
#define APP_EXIT_CODE_UNKNOWN_ACTION 4
#define APP_EXIT_CODE_ACTION_ERROR 5

#define APP_ARGS_MIN_COUNT 2
#define APP_ARGS_MAX_COUNT 3

#endif //GH_OS_H
